### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Houlistonm** [bagder/ca-bundle#10]
Can you add releases/tags to this repo for every new version of the bundle?
My use case is to consume the bundle in our project. 
A `github versioned resource` is better than `wgetting`  from the [curl website](https://curl.haxx.se/ca/cacert.pem) since wgetting places an unnecessary burden on the curl website.

**Comment by bagder** [comment]
Virtually every commit to this repo is a new bundle version. You can just do a "git pull" on a regular interval. What difference does it make if I make a tag or not?

> wgetting places an unnecessary burden on the curl website.

It really doesn't. Especially if you do that request conditionally and only download it if newer than the one you already have locally, there's really not a problem for our infra to handle that.

**Comment by Houlistonm** [comment]
The tag would trigger a build, as opposed to running on a schedule (daily?) and picking up the version du-jour.

I have a mature resource type that is based on tags/versions that I could re-use to trigger builds.
I don't have that capability for wgetting files.
The goal is to make this event driven.

**Comment by bagder** [comment]
So, trigger on a new push of the file. It only gets pushed when changed. Doing tags for every push seems excessive and pointless.
