### ISSUE TITLE
sha1 of real file does not match that printing in the file

### ISSUE THREAD

**Issue by ekeyme** [bagder/ca-bundle#2]
I download(also just copy&paste) the [ca-bundle.crt|](https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt), and then sha1sum it. Find out that sha1 of real file is _ecf8b8f6b31edf0e376b7e3b3a95f2d4e7b41c2d_, but sha1 value display in this file is _ed3c0bbfb7912bcc00cd2033b0cb85c98d10559c_. Is anything wrong?

**Comment by bagder** [comment]
The sha1sum included in the ca-bundle.crt output is for the downloaded certdata.txt. Did you verify that file?

**Comment by ekeyme** [comment]
@Daniel Stenberg
Thanks to replay.

Yeah! Sha1sum of the downloaded certdata.txt from 
http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt 
matches 'ed3c0bbfb7912bcc00cd2033b0cb85c98d10559c'.

Sorry, I have confused that meanings in the the ca-bundle.crt

**Comment by bagder** [comment]
Ok, cool. All good then!
